### ISSUE TITLE
How to hide the toast manually 

### ISSUE THREAD

**Issue by Vickneswaran** [gregttn/GTToast#3]
How to hide/dismiss the toast manually and is any provision to show the toast permanently for particular scenario.

**Comment by gregttn** [comment]
You were not able to dismiss the toast programmatically and still keep the animation. Few moments ago I pushed some changes which add `dismiss` method on the `GTToastView`. Here is how you can use it :

``` swift
var toast: GTToastView = GTToast.create("foo bar")
toast.show()

// later when you are ready
toast.dismiss()
```

I will release the new version of the pod and update the README later today. I will keep this issue open till then.

With regards to your second question, you can use `displayInterval` of the `GTToastConfig`. If you set it to a large value like `NSTimeIntervalSince1970` it will keep the toast displayed for long enough:)

**Comment by gregttn** [comment]
The new version of the pod (0.1.2) is now available:)
