### ISSUE TITLE
Min. Deployment Target to iOS 8.0

### ISSUE THREAD

**Issue by nkmadala** [gregttn/GTToast#5]
Hi, Is it possible for you to reduce the min. deployment target to 8.0 so that I can install this as a pod? I have compiled this with min. version as 8.0 and it works great.

**Comment by gregttn** [comment]
Hi,
I will consider this next time I release a new version.

Thanks

**Comment by gregttn** [comment]
Hi @nkmadala I deployed version 0.2.0 which allows  target to be set to 8.0

Thanks.
